# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 2592000
        gc_maxlifetime: 2592000

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
