twig:
    paths:
        'assets/images': images
        'assets/styles': styles
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_title: '%app.title%'
        app_version: '%app.version%'
when@test:
    twig:
        strict_variables: true
