controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_impressum:
    path: /impressum
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/impressum.html.twig'
app_privacy:
    path: /privacy
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/privacy.html.twig'